### ISSUE TITLE
TypeError: fig._transitions[fig._transition_state] is not a function

### ISSUE THREAD

**Issue by ArtPoon** [jlegewie/reveal.js-d3js-plugin#2]
Thanks for this great work - it's made it much easier for me to embed d3 animations into my reveal.js presentations.  While testing slides in my browser (Chrome 61.0.3163.100 on macOS), one of my animations locked and I got this message on the console:
```
d3js.js:83 Uncaught TypeError: fig._transitions[fig._transition_state] is not a function
    at HTMLDivElement.<anonymous> (d3js.js:83)
    at dispatchEvent (reveal.js:1534)
    at navigateFragment (reveal.js:3972)
    at nextFragment (reveal.js:3996)
    at navigateRight (reveal.js:4144)
    at HTMLDocument.onDocumentKeyDown (reveal.js:4358)
```
I'm putting a `try..catch` statement around line `83` to see if I can get more info.

**Comment by ArtPoon** [comment]
```javascript
        try {
            fig._transitions[fig._transition_state]();
        } catch(e) {
            console.log(fig._transitions);
            console.log(fig._transition_state);
        }
```
yielded the following:
```javascript
(2) [ƒ, ƒ]
 0: () => {…}
 1: () => {…}
 length: 2
 __proto__: Array(0)

-2
```

The `{...}` contain references to the respective `_transitions` functions in the JS.  I'm not sure how `fig._transition_state` ended up as `-2`.

**Comment by jlegewie** [comment]
Thanks for reporting. I won't have the time to investigate this anytime soon though. Probably when I work on my own presentations the next time. But feel free to post additional information here.

**Comment by ArtPoon** [comment]
Thanks @jlegewie -- I'll see what I can dig up.

**Comment by gcalmettes** [comment]
@ArtPoon I was able to reproduce and isolate the problem you encountered.
It happens when you go in `overview` mode (`ESC` key) while being on a slide past the one with the `D3` visualization.

- When the `overview` mode is launched, all the slides in the viewer are loaded, so the `fig._transition_state` variable is reset to zero again. 
- Because you're past the slide, then if you go out from the `overview` mode, and use the left key to go back to the slide in which the `D3` visualization is, then once on the slide, any left key press associated with a `d3-transition`will result in subtracting 1 to the `fig._transition_state` variable, and you end up with a negative `fig._transition_state`.

Adding
```
if (fig._transition_state < 0) {fig._transition_state = 0}
```

before 

```
fig._transitions[fig._transition_state]();
fig._transition_state = fig._transition_state + 1;
```

in the `fragmentshown` eventlistener will prevent the error to happen. However, only forward transition will work (you'll have to go back past the slide, and come back to it to see the transitions), since the `fig._transition_state` was reset to zero and so the last state of the visualization is lost when the `overview` mode is launched.

I'll try to see if there is a way to prevent a slide to be re-loaded when the `overview` mode is activated by pressing the `ESC` key.

**Comment by jlegewie** [comment]
Great! Did you also consider whether `Reveal.isOverview();` helps with this?

What would even be the correct behavior? For example, when the user selects an earlier slide from the overview?

**Comment by ArtPoon** [comment]
Thanks for the help, @gcalmettes!  Trying to reproduce with your example right now.

**Comment by ArtPoon** [comment]
Confirmed fix.  Thanks so much 👍 

*edit* sorry, I belatedly realized that you might want to keep this thread open for the `overview` mode aspect

**Comment by gcalmettes** [comment]
I will look how to implement the feature @ptamarit used in his [reveal-to-d3.js](https://github.com/ptamarit/slides-data-viz-web-d3/blob/master/src/js/reveal-to-d3.js) that prevents the initialization of the slide to be reset:

```
// Call the init function when arriving on a slide for the first time.
if (isSlideEvent) {
  var initFunction = functions.init;
  if (initFunction != null) {
    initFunction();
    // Make sure we don't call the init function again.
    functions.init = null;
  }
}
```

**Comment by gcalmettes** [comment]
@ArtPoon I ended up rewriting a plugin based on @jlegewie's work and supporting the `data-fragment-index` feature of Reveal.js. See [this repo](https://github.com/gcalmettes/reveal.js-d3).

**Comment by ArtPoon** [comment]
Fantastic, I can't wait to try it out!  Thanks to you both @gcalmettes and @jlegewie 👍
